package client.ui.clan;

import domen.Clan;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author luka
 */
public class PanelFormClan extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormClan
     */
    public PanelFormClan() {
        initComponents();
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(PanelFormClan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClan = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnLoad.setText("Učitaj");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel2.add(btnLoad);

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Izmeni");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnSearch.setText("Traži");
        jPanel2.add(btnSearch);

        txtSearch.setPreferredSize(new java.awt.Dimension(256, 25));
        jPanel2.add(txtSearch);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32000));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 85));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        tblClan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra", "Ime", "Prezime", "Korisničko ime", "Email", "Telefon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClan);
        if (tblClan.getColumnModel().getColumnCount() > 0) {
            tblClan.getColumnModel().getColumn(0).setResizable(false);
            tblClan.getColumnModel().getColumn(0).setPreferredWidth(12);
            tblClan.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(FormClan.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new CreateClan(null, true).setVisible(true);
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(FormClan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblClan.getSelectedRow();
        // Ako nije selektovan ni jedan red, gornja f-ja vraca vrednost -1
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Nije odabran ni jedan red!", "Sistem", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println(selectedRow);
        
        ClanTableModel ctm = (ClanTableModel) tblClan.getModel();
        new UpdateClan(null, true, ctm.getRowValue(selectedRow)).setVisible(true);
        
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(FormClan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClan;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    private void napuniTabelu() throws SQLException {
            List<Clan> lc = kontroleri.KontrolerClan.getList();
            tblClan.setModel(new ClanTableModel(lc));

        }
}
