package client.ui.faktura;

import domen.Faktura;
import domen.StavkaFakture;
import domen.Usluga;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import kontroleri.KontrolerFaktura;
import kontroleri.KontrolerTim;
import kontroleri.KontrolerUsluga;

/**
 *
 * @author luka
 */
public class PanelFormFaktura extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormFaktura
     */
    public PanelFormFaktura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWrapper = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFaktura = new javax.swing.JTable();
        pnlSidePanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        txtClanKontakt = new javax.swing.JTextField();
        txtClan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSponzorKontakt = new javax.swing.JTextField();
        txtRegBr = new javax.swing.JTextField();
        txtSponzor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPibJmbg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsluga = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        txtPdv = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnlWrapper.setLayout(new javax.swing.BoxLayout(pnlWrapper, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(309, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(1057, 40));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 4));

        jButton1.setText("Učitaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Dodaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Traži");
        jPanel1.add(jButton3);

        jTextField1.setPreferredSize(new java.awt.Dimension(256, 25));
        jPanel1.add(jTextField1);

        pnlWrapper.add(jPanel1);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(16, 40));

        tblFaktura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFaktura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFakturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFaktura);

        pnlWrapper.add(jScrollPane2);

        add(pnlWrapper);

        pnlSidePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlSidePanel.setMaximumSize(new java.awt.Dimension(420, 131068));
        pnlSidePanel.setMinimumSize(new java.awt.Dimension(400, 20));
        pnlSidePanel.setPreferredSize(new java.awt.Dimension(400, 720));
        pnlSidePanel.setLayout(new javax.swing.BoxLayout(pnlSidePanel, javax.swing.BoxLayout.PAGE_AXIS));

        txtTim.setEditable(false);

        txtClanKontakt.setEditable(false);

        txtClan.setEditable(false);
        txtClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClanActionPerformed(evt);
            }
        });

        jLabel17.setText("Izdavalac");

        jLabel18.setText("Org. jedinica");

        jLabel19.setText("Kontakt");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClan)
                    .addComponent(txtClanKontakt)
                    .addComponent(txtTim)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(0, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClanKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSidePanel.add(jPanel7);

        txtSponzorKontakt.setEditable(false);

        txtRegBr.setEditable(false);

        txtSponzor.setEditable(false);

        jLabel13.setText("Primalac (Sponzor)");

        jLabel14.setText("Kontakt");

        jLabel15.setText("Reg. Broj");

        txtPibJmbg.setEditable(false);
        txtPibJmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPibJmbgActionPerformed(evt);
            }
        });

        jLabel16.setText("Pib (JMBG za Fiz. lica)");

        tblUsluga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsluga.setPreferredSize(new java.awt.Dimension(128, 80));
        jScrollPane3.setViewportView(tblUsluga);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSponzor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSponzorKontakt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRegBr, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(122, 122, 122))
                            .addComponent(txtPibJmbg))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPibJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSponzorKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSidePanel.add(jPanel6);

        jPanel8.setMaximumSize(new java.awt.Dimension(32222, 32767));
        jPanel8.setPreferredSize(new java.awt.Dimension(454, 230));

        txtTotal.setEditable(false);

        txtPdv.setEditable(false);

        txtCena.setEditable(false);

        jLabel20.setText("Sumirana cena stavki");

        jLabel21.setText("Ukupna cena");

        jLabel22.setText("PDV");

        txtPopust.setEditable(false);

        jLabel23.setText("Popust");

        jLabel24.setText("Datum izdavanja");

        txtDatum.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCena)
                    .addComponent(txtTotal)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPdv, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(122, 122, 122))
                            .addComponent(txtPopust)))
                    .addComponent(txtDatum)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlSidePanel.add(jPanel8);

        add(pnlSidePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClanActionPerformed

    private void txtPibJmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPibJmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPibJmbgActionPerformed

    private void tblFakturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFakturaMouseClicked
        // TODO add your handling code here:
                FakturaTableModel ftm = (FakturaTableModel) tblFaktura.getModel();
        Faktura selektovana = ftm.getFromRow(tblFaktura.getSelectedRow());
        try {
            napuniTabeluUsluga(selektovana);
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //
        
        Double osnovnaCena = selektovana.getOsnovnaCena();
        Double pdv = selektovana.getPdv();
        Double popust = selektovana.getPopust();
        Double total = osnovnaCena + pdv - popust;
        
        // Postaviti vrednosti u polja za pregled
        
        txtClan.setText(selektovana.getClan().toString()); 
        txtClanKontakt.setText(selektovana.getClan().getTelefon());
        
        try {
            // TODO:
            txtTim.setText(KontrolerTim.getTimFromClan(selektovana.getClan()).getNaziv());
        } catch (SQLException ex) {
            Logger.getLogger(PanelFormFaktura.class.getName()).log(Level.WARNING, null, ex);
        } finally {
            
            txtSponzor.setText(selektovana.getSponzor().toString());
            txtSponzorKontakt.setText(selektovana.getSponzor().getKontakt());
            txtCena.setText(osnovnaCena.toString());
            txtPdv.setText(pdv.toString());
            txtPopust.setText(popust.toString());
            txtTotal.setText(total.toString());
            txtDatum.setText(selektovana.getDatum().toString());
        }
    }//GEN-LAST:event_tblFakturaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CreateFaktura(null, true).setVisible(true);
        try {
            napuniTabelu();
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlSidePanel;
    private javax.swing.JPanel pnlWrapper;
    private javax.swing.JTable tblFaktura;
    private javax.swing.JTable tblUsluga;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtClan;
    private javax.swing.JTextField txtClanKontakt;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtPdv;
    private javax.swing.JTextField txtPibJmbg;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtRegBr;
    private javax.swing.JTextField txtSponzor;
    private javax.swing.JTextField txtSponzorKontakt;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void napuniTabelu() throws SQLException {
        List<Faktura> lf = KontrolerFaktura.getList();
        tblFaktura.setModel(new FakturaTableModel(lf));

    }

    private void napuniTabeluUsluga(Faktura selektovana) throws SQLException {
        List<StavkaFakture> lsf = selektovana.getListaStavkaFakture();
        tblUsluga.setModel(new StavkaFaktureTableModel(lsf));
    }
}
