package client.ui.tim;

import client.ui.clan.FormClan;
import domen.Clan;
import domen.Tim;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author luka
 */
public class PanelFormTim extends javax.swing.JPanel {

    /**
     * Creates new form PanelFormTim
     */
    public PanelFormTim() {
        initComponents();
        try {
            napuniTabeluTim();
        } catch (SQLException ex) {
            Logger.getLogger(FormTim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTim = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnUbaci = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClan = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnLoad.setText("Učitaj");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel2.add(btnLoad);

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Izmeni");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnSearch.setText("Traži");
        jPanel2.add(btnSearch);

        jTextField1.setPreferredSize(new java.awt.Dimension(256, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        tblTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra", "Naziv"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTimMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTim);

        jPanel1.add(jScrollPane1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnUbaci.setText("Dodaj člana u tim");
        btnUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbaciActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbaci);

        jPanel1.add(jPanel3);

        tblClan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Šifra", "Ime", "Prezime", "Korisničko ime", "Email", "Telefon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClan);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {
            napuniTabeluTim();
        } catch (SQLException ex) {
            Logger.getLogger(FormTim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new CreateTim(null, true).setVisible(true);
        try {
            napuniTabeluTim();
        } catch (SQLException ex) {
            // TODO: Dopisati
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblTim.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Nije odabran red!", "Sistem", JOptionPane.WARNING_MESSAGE);
            return;
        }
        new UpdateTim(null, true, new Tim((Long) tblTim.getValueAt(row, 0), (String) tblTim.getValueAt(row, 1))).setVisible(true);
        try {
            napuniTabeluTim();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbaciActionPerformed
        new CreateClanTim(null, true).setVisible(true);

    }//GEN-LAST:event_btnUbaciActionPerformed

    private void tblTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTimMouseClicked
        int row = tblTim.getSelectedRow();
        if (row < 0) {
            return;
        }

        try {
            napuniTabeluClan(new Tim((Long) tblTim.getValueAt(row, 0), (String) tblTim.getValueAt(row, 1)));
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_tblTimMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUbaci;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblClan;
    private javax.swing.JTable tblTim;
    // End of variables declaration//GEN-END:variables

    private void napuniTabeluClan(Tim tim) throws SQLException {
        List<Clan> lc = kontroleri.KontrolerClanTim.getClanoviTima(tim);
        TableModel tm = tblClan.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);
        for (Clan c : lc) {
            Object[] row = new Object[]{
                c.getId(),
                c.getIme(),
                c.getPrezime(),
                c.getKorisnickoIme(),
                c.getEmail(),
                c.getTelefon()
            };
            dtm.addRow(row);
        }

    }

    private void napuniTabeluTim() throws SQLException {
        List<Tim> lt = kontroleri.KontrolerTim.getList();
        TableModel tm = tblTim.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);
        for (Tim t : lt) {
            Object[] row = new Object[]{
                t.getId(),
                t.getNaziv()
            };
            dtm.addRow(row);
        }

    }
}
